export default [
    {id: 'luigi', name: 'Luigi'},
    {id: 'peach', name: 'Peach'},
    {id: 'bowser', name: 'Bowser'},
    {id: 'yoshi', name: 'Yoshi'},
    {id: 'rosalina', name: 'Rosalina and Luma'},
    {id: 'bowserjr', name: 'Bowser Jr'},
    {id: 'wario', name: 'Wario'},
    {id: 'dk', name: 'Donkey Kong'},
    {id: 'ddk', name: 'Diddy Kong'},
    {id: 'gnw', name: 'Game and Watch'},
    {id: 'littlemac', name: 'Little Mac'},
    {id: 'link', name: 'Link'},
    {id: 'zelda', name: 'Zelda'},
    {id: 'shiek', name: 'Shiek'},
    {id: 'ganon', name: 'Ganondorf'},
    {id: 'younglink', name: 'Young Link'},
    {id: 'samus', name: 'Samus'},
    {id: 'zss', name: 'Zero Suit Samus'},
    {id: 'pit', name: 'Pit'},
    {id: 'palutena', name: 'Palutena'},
    {id: 'marth', name: 'Marth'},
    {id: 'ike', name: 'Ike'},
    {id: 'robin', name: 'Robin'},
    {id: 'mario', name: 'Mario'},
    {id: 'duckhunt', name: 'Duck Hunt'},
    {id: 'kirby', name: 'Kirby'},
    {id: 'dedede', name: 'King Dedede'},
    {id: 'metaknight', name: 'Metaknight'},
    {id: 'fox', name: 'Fox'},
    {id: 'falco', name: 'Falco'},
    {id: 'pikachu', name: 'Pikachu'},
    {id: 'charizard', name: 'Charizard'},
    {id: 'lucario', name: 'Lucario'},
    {id: 'jiggly', name: 'Jigglypuff'},
    {id: 'greninja', name: 'Greninja'},
    {id: 'rob', name: 'Rob'},
    {id: 'ness', name: 'Ness'},
    {id: 'falcon', name: 'Captain Falcon'},
    {id: 'villager', name: 'Villager'},
    {id: 'olimar', name: 'Olimar'},
    {id: 'wft', name: 'Wii Fit Trainer'},
    {id: 'shulk', name: 'Shulk'},
    {id: 'drmario', name: 'Dr Mario'},
    {id: 'darkpit', name: 'Dark Pit'},
    {id: 'lucina', name: 'Lucina'},
    {id: 'pacman', name: 'Pac Man'},
    {id: 'megaman', name: 'Megaman'},
    {id: 'sonic', name: 'Sonic'},
    {id: 'mewtwo', name: 'Mewtwo'},
    {id: 'lucas', name: 'Lucas'},
    {id: 'roy', name: 'Roy'},
    {id: 'ryu', name: 'Ryu'},
    {id: 'cloud', name: 'Cloud'},
    {id: 'corrin', name: 'Corrin'},
    {id: 'bayo', name: 'Bayonetta'},
    {id: 'miibrawler', name: 'Mii Brawler'},
    {id: 'miigunner', name: 'Mii Gunner'},
    {id: 'miiswordfighter', name: 'Mii Sword Fighter'}
]
