const char = id => ({id, img: require(`./img/${id}.png`)})
export default [
    {...char('bayonetta'), name: 'Bayonetta'},
    {...char('bowser'), name: 'Bowser'},
    {...char('bowserjr'), name: 'Bowser Jr'},
    {...char('captainfalcon'), name: 'Captain Falcon'},
    {...char('charizard'), name: 'Charizard'},
    {...char('cloud'), name: 'Cloud'},
    {...char('corrin'), name: 'Corrin'},
    {...char('darkpit'), name: 'Dark Pit'},
    {...char('diddykong'), name: 'Diddy Kong'},
    {...char('donkeykong'), name: 'Donkey Kong'},
    {...char('drmario'), name: 'Dr Mario'},
    {...char('duckhunt'), name: 'Duck Hunt'},
    {...char('falco'), name: 'Falco'},
    {...char('fox'), name: 'Fox'},
    {...char('ganondorf'), name: 'Ganondorf'},
    {...char('greninja'), name: 'Greninja'},
    {...char('ike'), name: 'Ike'},
    {...char('jigglypuff'), name: 'Jigglypuff'},
    {...char('kirby'), name: 'Kirby'},
    {...char('kingdedede'), name: 'King Dedede'},
    {...char('link'), name: 'Link'},
    {...char('littlemac'), name: 'Little Mac'},
    {...char('lucario'), name: 'Lucario'},
    {...char('lucas'), name: 'Lucas'},
    {...char('lucina'), name: 'Lucina'},
    {...char('luigi'), name: 'Luigi'},
    {...char('mario'), name: 'Mario'},
    {...char('marth'), name: 'Marth'},
    {...char('megaman'), name: 'Megaman'},
    {...char('metaknight'), name: 'Metaknight'},
    {...char('mewtwo'), name: 'Mewtwo'},
    {...char('miibrawler'), name: 'Mii Brawler'},
    {...char('miigunner'), name: 'Mii Gunner'},
    {...char('miisword'), name: 'Mii Sword Fighter'},
    {...char('mrgamewatch'), name: 'Mr Game and Watch'},
    {...char('ness'), name: 'Ness'},
    {...char('olimar'), name: 'Olimar'},
    {...char('pacman'), name: 'Pac Man'},
    {...char('palutena'), name: 'Palutena'},
    {...char('peach'), name: 'Peach'},
    {...char('pikachu'), name: 'Pikachu'},
    {...char('pit'), name: 'Pit'},
    {...char('rob'), name: 'Rob'},
    {...char('robin'), name: 'Robin'},
    {...char('rosalinaluma'), name: 'Rosalina and Luma'},
    {...char('roy'), name: 'Roy'},
    {...char('ryu'), name: 'Ryu'},
    {...char('samus'), name: 'Samus'},
    {...char('sheik'), name: 'Sheik'},
    {...char('shulk'), name: 'Shulk'},
    {...char('sonic'), name: 'Sonic'},
    {...char('toonlink'), name: 'Toon Link'},
    {...char('villager'), name: 'Villager'},
    {...char('wario'), name: 'Wario'},
    {...char('wiifittrainer'), name: 'Wii Fit Trainer'},
    {...char('yoshi'), name: 'Yoshi'},
    {...char('zelda'), name: 'Zelda'},
    {...char('zerosuitsamus'), name: 'Zero Suit Samus'}
]
